### ISSUE TITLE
Not reading hiera keys as demonstrated in your README

### ISSUE THREAD

**Issue by LinguineCode** [wolfspyre/puppet-bashrc#1]
Thank you for the module. I plan to use it to change bash prompt colors depending on whether you are in production environment as a visual warning to sysadmins to be extra careful

Your module seems to "ignore" my hiera keys and only sets the default blue/white. Below is the relevant code I am using. Straight from your README:

bashrc_prompt_color_enable:    'enabled'
bashrc_prompt_primary_color:   'blue'
bashrc_prompt_secondary_color: 'red'

**Comment by LinguineCode** [comment]
Also it seems that I have to include the following 3 classes, rather than just include 1 ('bashrc') which includes the other 2

classes: [ 'bashrc', 'bashrc::params', 'bashrc::promptcolor' ]

**Comment by wolfspyre** [comment]
Thanks for the information! I'm going to be refactoring this module shortly
to accommodate debian as well, and I'll get this sorted out at that time.

(PRs are welcome in the meantime; but I will get to this)

**Comment by wolfspyre** [comment]
I've fixed this with the current refactor. Please test it out and let me know if this is easier to work with
