### ISSUE TITLE
default parameters

### ISSUE THREAD

**Issue by visibilityspots** [wolfspyre/puppet-bashrc#4]
It would be much nicer to set the defaults in your params.pp to false and give the users of your module the availability to chose themselves to enable the params they need.

I got the "we were not given a process to search for as an argument, and no config files are present. failing" error and did not know from where it came...

**Comment by wolfspyre** [comment]
https://github.com/wolfspyre/puppet-bashrc/commit/e5ebfe6eb344fbfae4fc836fafef5cf1c9ad4ad1 should address this. Thanks for the suggestion
